<?php
/**
 * The file that defines the Home Page custom fields
 *
 * @link       https://github.com/AgriLife/agrilife-today/blob/master/fields/home.php
 * @since      0.1.7
 * @package    agrilife-today
 * @subpackage agrilife-today/fields
 */

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5cae401b57ab6',
			'title'                 => 'Home',
			'fields'                => array(
				array(
					'key'               => 'field_5da7547bd0db0',
					'label'             => 'Stories',
					'name'              => 'stories',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Add Story Section',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5da74e24d0da7',
							'label'             => '',
							'name'              => 'stories',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_5da74e24d0da8',
									'label'             => 'Heading',
									'name'              => 'heading',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5da74e24d0da9',
									'label'             => 'Stories',
									'name'              => 'stories',
									'type'              => 'flexible_content',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'layouts'           => array(
										'layout_5cae4470ad4f9' => array(
											'key'        => 'layout_5cae4470ad4f9',
											'name'       => 'post',
											'label'      => 'Post',
											'display'    => 'block',
											'sub_fields' => array(
												array(
													'key'  => 'field_5da74f6ad0daf',
													'label' => 'Post',
													'name' => 'post',
													'type' => 'post_object',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'post_type' => '',
													'taxonomy' => '',
													'allow_null' => 1,
													'multiple' => 0,
													'return_format' => 'object',
													'ui'   => 1,
												),
												array(
													'key'  => 'field_5da7661d1e012',
													'label' => 'Description',
													'name' => 'description',
													'type' => 'textarea',
													'instructions' => '',
													'required' => 1,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'maxlength' => '',
													'rows' => 6,
													'new_lines' => '',
												),
											),
											'min'        => '',
											'max'        => '',
										),
										'layout_5cae475dc97a7' => array(
											'key'        => 'layout_5cae475dc97a7',
											'name'       => 'quote',
											'label'      => 'Quote',
											'display'    => 'block',
											'sub_fields' => array(
												array(
													'key'  => 'field_5da8717347591',
													'label' => 'Post',
													'name' => 'post',
													'type' => 'post_object',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'post_type' => '',
													'taxonomy' => '',
													'allow_null' => 1,
													'multiple' => 0,
													'return_format' => 'object',
													'ui'   => 1,
												),
												array(
													'key'  => 'field_5da74e24d0dab',
													'label' => 'Quote',
													'name' => 'quote',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'basic',
													'media_upload' => 0,
													'delay' => 0,
												),
											),
											'min'        => '',
											'max'        => '',
										),
									),
									'button_label'      => 'Add Story',
									'min'               => 1,
									'max'               => 3,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_5da754b9d0db1',
					'label'             => 'In The News',
					'name'              => 'in_the_news',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5da754c7d0db2',
							'label'             => 'Heading',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'In the news',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5da754dad0db3',
							'label'             => 'Stories',
							'name'              => 'stories',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'block',
							'button_label'      => 'Add Story',
							'sub_fields'        => array(
								array(
									'key'               => 'field_5ee79b69b5429',
									'label'             => 'Post',
									'name'              => 'post',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'in-the-news',
									),
									'taxonomy'          => '',
									'allow_null'        => 1,
									'multiple'          => 0,
									'return_format'     => 'object',
									'ui'                => 1,
								),
								array(
									'key'               => 'field_5da754fed0db4',
									'label'             => 'Logo',
									'name'              => 'logo',
									'type'              => 'image',
									'instructions'      => 'Choose a logo representing the news agency',
									'required'          => 1,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_5ee79b69b5429',
												'operator' => '==empty',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
									'preview_size'      => 'thumbnail',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
								array(
									'key'               => 'field_5da75547d0db5',
									'label'             => 'Title',
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_5ee79b69b5429',
												'operator' => '==empty',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5da75573d0db6',
									'label'             => 'Description',
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_5ee79b69b5429',
												'operator' => '==empty',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => 6,
									'new_lines'         => '',
								),
								array(
									'key'               => 'field_5da755b4d0db7',
									'label'             => 'Link',
									'name'              => 'link',
									'type'              => 'url',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_5ee79b69b5429',
												'operator' => '==empty',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_5db9c397a1237',
					'label'             => 'Subscribe',
					'name'              => 'subscribe',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 1,
					'delay'             => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_template',
						'operator' => '==',
						'value'    => 'templates/home.php',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

endif;
